### ISSUE TITLE
Cleaning up the repo a bit

### ISSUE THREAD

**Issue by zvonimir** [soarlab/AAQNN#1]
We should:
- Remove pycache folders from github. No need to have those version controlled
- Organize scripts so that they are not in the top level folder
- Write a short document describing what each folder contains. The structure is unclear at this point.
Given that we are probably going to leverage this code for quite a bit, it would be good to clean it up somewhat.

**Comment by martinmatak** [comment]
Pycache removed: https://github.com/soarlab/AAQNN/pull/2
Organization of the project separated in new issue: https://github.com/soarlab/AAQNN/issues/3

so that we have 1 PR per issue
